function [table_series_final, path_table_nii] = munge_raw(config)
%--------------------------------------------------------------------------
% Read filename information from raw image directories. Can contain .tif
% files from light-sheet or multiple .nii file formats for MRI images. 
%
% These are all possible image extensions we're able to read:
% ext = [".tif",".tiff",".nii",".nrrd",".nhdr",".mhd"];
%--------------------------------------------------------------------------
% Usage:
% [path_table_series, path_table_nii] = munge_raw(config);
%
% Inputs:
% config: Configuration structure generated by NM_config using any stage.
%
% Outputs:
% path_table_series: Table with munged .tif series.
%
% path_table_nii: Table with munged .nii files.
%--------------------------------------------------------------------------
% Added by Rene:
% Read filename information from two-level folder hierarchy (TeraStitcher)
%--------------------------------------------------------------------------

% These are all possible image extensions we're able to read
ext = [".tif",".tiff",".nii",".nrrd",".nhdr",".mhd"];

% Get list of all files in all sub_directories
if length(config.img_directory) == 1
    all_files = [dir(fullfile(config.img_directory,'**/*.tif')); ...
                 dir(fullfile(config.img_directory,'**/*.tiff')); ...
                 dir(fullfile(config.img_directory,'**/*.nii')); ...
                 dir(fullfile(config.img_directory,'**/*.nrrd')); ...
                 dir(fullfile(config.img_directory,'**/*.nhdr')); ...
                 dir(fullfile(config.img_directory,'**/*.mhd'))];
else
    assert(length(config.img_directory)<=length(config.markers),"More image "+...
        "directories specified than there are markers")
    all_files = cell(1,length(config.img_directory));
    for i = 1:length(config.img_directory)
        assert(isfolder(config.img_directory(i)), "Directory %s dose not exist",...
            config.img_directory(i));
        all_files{i} = dir(fullfile(config.img_directory(i),'*.*'));
    end
    all_files = cat(1,all_files{:});
    names_tmp = {all_files.name}';
    all_files = all_files(contains(names_tmp, ext));
end

% Remove output directory folder
if config.img_directory == config.output_directory
    error("Input image directory cannot match output directory")
else
    % all_files = all_files(arrayfun(@(s) ~isequal(s.folder,...
        % config.output_directory,'IgnoreCase',true),all_files));
    % modified; Rene
    full_paths = strcat({all_files.folder}', '/', {all_files.name}');
    all_files = all_files(~contains(full_paths, config.output_directory, 'IgnoreCase', true));
end

% Get which image extensions are present and subset these images
names_all = {all_files.name}';
idx = false(length(ext), length(all_files));
for i = 1:length(ext)
    idx(i,:) = contains(names_all, ext(i));
end
ext_here = ext(any(idx,2));

% Read nifiti file formats if present
nifti_ext = ext_here(~ismember(ext_here,[".tif",".tiff"]));
if ~isempty(nifti_ext) && isfield(config,'mri_channels')
    nifti_files = all_files(any(idx(3:end,:)));
    path_table_nii = munge_nifti_raw(nifti_files,config);
else
    path_table_nii = [];
end

% Subset tif files
% Divide into different folders
tiff_files = all_files(any(idx(1:2,:)));

% Return if no .tif files present
if isempty(tiff_files)
    warning("No raw .tif files detected in image directories") 
    table_series_final = [];
    return
end

% If specified, remove channels without channel number
if isfield(config,'channel_num') && ~isempty(config.channel_num)
    idx = false(length(tiff_files),1);
    c_idx = cell(1,length(config.channel_num));
    tiff_full = strcat({tiff_files.folder}', '/', {tiff_files.name}');
    for i = 1:length(config.channel_num)
        a = contains(tiff_full, config.channel_num(i));
        b = a & contains(tiff_full, config.markers(i));
        if ~isempty(b) && any(b)
            c_idx{i} = b;
            idx = idx | b;
        else
            c_idx{i} = a;
            idx = idx | a;
        end
    end
    tiff_files = tiff_files(idx);
    c_idx = cellfun(@(s) s(idx),c_idx,'UniformOutput',false);
end

tiff_folders = unique({tiff_files.folder});
tiff_names = {tiff_files.name}';
tiff_folder_arr = {tiff_files.folder}';

% Try matching folders by channel number, then by folder name, then by
% marker name in file <-- not applicable for hiararchy input
path_table_series = cell(1,length(config.markers));
files_read = false;
if length(tiff_folders) == length(config.markers)
    % Unique marker per folder
    for i = 1:length(tiff_folders)
        path_idx = [];
        % Check channel num
        if isfield(config,'channel_num') && ~isempty(config.channel_num)
            path_idx = tiff_files(c_idx{i});
        end
        % Check folder name
        if isempty(path_idx)
            path_idx = tiff_files(contains(tiff_folder_arr, config.markers(i)));
        end
        % Check for unique marker names in filename
        if isempty(path_idx)
            path_idx = tiff_files(contains(tiff_names, config.markers(i)));
        end
        % Finally, just assign this folder to marker based on index
        if isempty(path_idx)
            path_idx = tiff_files(strcmp(tiff_folder_arr, tiff_folders{i}));
        end

        % Use regular expressions to extract information and save
        path_table_series{i} = get_table_struct(path_idx, config.sample_id, config.markers(i), i, config.position_exp);
    end
    files_read = true;
else
    % Marker w/ multiple folders added by Rene
    for i = 1:length(config.markers)
        path_idx = [];
        % Check channel num
        if isfield(config,'channel_num') && ~isempty(config.channel_num)
            path_idx = tiff_files(c_idx{i});
        end
        % Check folder name
        if isempty(path_idx)
            path_idx = tiff_files(contains(tiff_folder_arr, config.markers(i)));
        end
        % Check for unique marker names in filename
        if isempty(path_idx)
            path_idx = tiff_files(contains(tiff_names, config.markers(i)));
        end
        % Finally, just assign this folder to marker based on index
        if isempty(path_idx)
            path_idx = tiff_files(strcmp(tiff_folder_arr, tiff_folders{i}));
        end

        % Use regular expressions to extract information and save
        path_table_series{i} = get_table_struct(path_idx, config.sample_id, config.markers(i), i, config.position_exp);
    end
end

% More complicated scenario
% Different number of folders and markers present
if ~files_read && isfield(config,'channel_num') && ~isempty(config.channel_num)
    % Channel numbers provided to read multiple channels in the same folder
    for i = 1:length(c_idx)
        path_idx = tiff_files(c_idx{i});
        
        % Use regular expressions to extract information and save 
        path_table_series{i} = get_table_struct(path_idx, config.sample_id, config.markers(i), i, config.position_exp);
    end    
elseif ~files_read
    % Finally check if each folder and/or filename has unique marker, 
    % otherwise give error
    
    % Check files for marker name in the filename
    c_idx = false(length(config.markers), length(tiff_files));
    f_idx = false(1, length(config.markers));
    for i = 1:length(config.markers)
        c_idx(i,:) = contains(tiff_names, config.markers(i));
        f_idx(i) = any(contains(tiff_folders, config.markers(i)));
    end

    if ~any(sum(c_idx) > 1)
        % If unique marker present in each filename
        for i = 1:length(config.markers)
            path_idx = tiff_files(c_idx(i,:));

            % Use regular expressions to extract information and save
            path_table_series{i} = get_table_struct(path_idx, config.sample_id, config.markers(i), i, config.position_exp);
        end
    elseif all(f_idx)
        for i = 1:length(config.markers)
            f = contains(tiff_folders, config.markers(i));
            path_idx = tiff_files(strcmp(tiff_folder_arr, tiff_folders{f}));
            
            % Use regular expressions to extract information and save 
            path_table_series{i} = get_table_struct(path_idx, config.sample_id, config.markers(i), i, config.position_exp);
        end
    else
        error("Channel number indexes or unique folders for each marker are needed to import these images")
    end
end

% Create table for each marker
for i = 1:length(path_table_series)
    table_series = struct2table(path_table_series{i});
   
    if isequal(config.hierarchy_input,"false")
        % Set x,y,z positions to start at 1
        if ~iscell(table_series.y)
            table_series.y = table_series.y - min(table_series.y)+1;
        else
            table_series.y = ones(height(table_series),1);
        end
        if ~iscell(table_series.x)
            table_series.x = table_series.x - min(table_series.x)+1;
        else
            table_series.x = ones(height(table_series),1);
        end

        table_series.z = table_series.z - min(table_series.z)+1;

        % Trim any additional characters appended
        table_series.file = cellfun(@(s) extractBefore(s,'.tif') + ".tif", table_series.file);
        %table_series.file = cellfun(@(s) strrep(s, '/@eaDir',''), table_series.file, 'UniformOutput',false);

    else
        % Input as a two-level hierarchy of folders; Rene
        table_series.y_pos = table_series.y;
        table_series.x_pos = table_series.x;
        table_series.z_pos = table_series.z;

        % Jitter tolerance: coordinates in units of 0.1 um, so 15 um = 150 units.
        jitter_tolerance = 150;

        % Snap raw coordinates to a canonical grid before normalization.
        % This collapses jittered coordinates (e.g. 340600 vs 340700) so that
        % unique() returns the correct number of tile positions and step_x/y
        % are computed correctly.  For channels after the first, snap to the
        % reference channel grid; for the first channel, cluster internally so
        % that tiles within jitter_tolerance of each other share one value.
        if i > 1 && isfield(table_series_final, config.markers(1))
            ref_table = table_series_final.(config.markers(1));
            ref_tiles  = unique([ref_table.y_pos, ref_table.x_pos], 'rows');
            cur_tiles  = unique([table_series.y_pos, table_series.x_pos], 'rows');
            for t = 1:size(cur_tiles, 1)
                ty = cur_tiles(t, 1);
                tx = cur_tiles(t, 2);
                dists = sqrt((double(ref_tiles(:,1)) - double(ty)).^2 + ...
                             (double(ref_tiles(:,2)) - double(tx)).^2);
                [min_dist, closest_idx] = min(dists);
                tile_mask = table_series.y_pos == ty & table_series.x_pos == tx;
                if min_dist > 0 && min_dist <= jitter_tolerance
                    fprintf("%s\t Channel %s tile (y_pos=%d, x_pos=%d) snapped to " + ...
                        "reference (y_pos=%d, x_pos=%d) [jitter: %.1f um]\n", ...
                        datetime('now'), config.markers(i), ty, tx, ...
                        ref_tiles(closest_idx,1), ref_tiles(closest_idx,2), min_dist/10);
                    table_series.y_pos(tile_mask) = ref_tiles(closest_idx, 1);
                    table_series.x_pos(tile_mask) = ref_tiles(closest_idx, 2);
                elseif min_dist > jitter_tolerance
                    warning("Channel %s tile (y_pos=%d, x_pos=%d) is %.1f um from " + ...
                        "nearest reference tile (tolerance: %.0f um). Tile not matched.", ...
                        config.markers(i), ty, tx, min_dist/10, jitter_tolerance/10);
                end
            end
        else
            % First channel: cluster internally so jittered tiles share a
            % canonical coordinate.  Sort unique positions and merge any two
            % that are closer than jitter_tolerance.
            table_series.y_pos = cluster_coords(table_series.y_pos, jitter_tolerance);
            table_series.x_pos = cluster_coords(table_series.x_pos, jitter_tolerance);
        end

        % Now compute step from the snapped/clustered coordinates.
        tmp_y = unique(table_series.y_pos);
        if length(tmp_y) > 1
            step_y = (max(tmp_y) - min(tmp_y))/(length(tmp_y) - 1);
        else
            step_y = 1;
        end
        tmp_x = unique(table_series.x_pos);
        if length(tmp_x) > 1
            step_x = (max(tmp_x) - min(tmp_x))/(length(tmp_x) - 1);
        else
            step_x = 1;
        end
        tmp_z = unique(table_series.z_pos);
        if length(tmp_z) > 1
            step_z = (max(tmp_z) - min(tmp_z))/(length(tmp_z) - 1);
        else
            step_z = 1;
        end

        % Copy snapped positions back to y/x/z before normalizing.
        table_series.y = table_series.y_pos;
        table_series.x = table_series.x_pos;
        table_series.z = table_series.z_pos;

        if isequal(config.y_top2bottom,"false")
            table_series.y = -table_series.y;
        end
        if isequal(config.x_left2right,"false")
            table_series.x = -table_series.x;
        end

        table_series.y = round((table_series.y - min(table_series.y))/step_y) + 1;
        table_series.x = round((table_series.x - min(table_series.x))/step_x) + 1;
        table_series.z = round((table_series.z - min(table_series.z))/step_z) + 1;

        % For channels after the first, replace normalized indices with the
        % reference channel's indices (guarantees identical tile numbering
        % even when the reference and current channels have different raw
        % coordinate offsets due to residual floating-point rounding).
        if i > 1 && isfield(table_series_final, config.markers(1))
            ref_table = table_series_final.(config.markers(1));
            cur_tiles = unique([table_series.y_pos, table_series.x_pos], 'rows');
            for t = 1:size(cur_tiles, 1)
                ty = cur_tiles(t, 1);
                tx = cur_tiles(t, 2);
                tile_mask = table_series.y_pos == ty & table_series.x_pos == tx;
                ref_mask  = ref_table.y_pos == ty & ref_table.x_pos == tx;
                if any(ref_mask)
                    ref_y_idx = unique(ref_table.y(ref_mask));
                    ref_x_idx = unique(ref_table.x(ref_mask));
                    if isscalar(ref_y_idx) && isscalar(ref_x_idx)
                        table_series.y(tile_mask) = ref_y_idx;
                        table_series.x(tile_mask) = ref_x_idx;
                    end
                end
            end
        end

    end

    table_series_final.(config.markers(i)) = table_series;

end

end


function paths_nifti = munge_nifti_raw(nifti_files, config)
% Create structure for nifiti files. Assumed to single tile, single
% channel, multi-slice. Must contain a marker in the filename

file = cell(1,length(nifti_files));
marker = repmat("",1,length(nifti_files));
channel_num = zeros(1,length(nifti_files));
y_res = zeros(1,length(nifti_files));
x_res = zeros(1,length(nifti_files));
z_res = zeros(1,length(nifti_files));

% Subset only images with marker present
idx=1;
for i = 1:length(config.mri_channels)
    sub = nifti_files(arrayfun(@(s) contains(s.name,config.mri_channels(i)),nifti_files));
    for j = 1:length(sub)
       file{idx} = fullfile(sub(j).folder,sub(j).name);
       marker(idx) = config.mri_channels(i);
       channel_num(idx) = i;
       y_res(idx) = config.mri_resolution;
       x_res(idx) = config.mri_resolution;
       z_res(idx) = config.mri_resolution;
       idx = idx+1;
    end
end

% Create table
paths_nifti = table('Size',[length(1:idx-1), 7],...
    'VariableTypes',{'cell','string','string','string','double','double','double'},...
    'VariableNames',{'file','sample_id','marker','channel_num','x_res','y_res','z_res'});

paths_nifti.file = file(1:idx-1)';
paths_nifti.sample_id = repmat(config.sample_id,idx-1,1);
paths_nifti.marker = marker(1:idx-1)';
paths_nifti.channel_num = channel_num(1:idx-1)';
paths_nifti.y_res = y_res(1:idx-1)';
paths_nifti.x_res = x_res(1:idx-1)';
paths_nifti.z_res = z_res(1:idx-1)';

end


function path_sub = get_table_struct(path_idx, sample_id, marker, channel, position_exp)

n = length(path_idx);
files = fullfile({path_idx.folder}, {path_idx.name})';
names = {path_idx.name}';

if length(position_exp) == 1
    position_exp = horzcat(["", ""], position_exp);
end

use_hierarchy = isempty(position_exp);
y_vals = zeros(n, 1);
x_vals = zeros(n, 1);
z_vals = zeros(n, 1);

% Process in chunks so the progress bar updates incrementally
chunk_size = 5000;
n_chunks = max(1, ceil(n / chunk_size));
bar_width = 30;
fprintf('  Parsing %d %s files: [%s]   0%%', n, marker, repmat(' ', 1, bar_width));
for k = 1:n_chunks
    i1 = (k-1)*chunk_size + 1;
    i2 = min(k*chunk_size, n);
    sub = i1:i2;
    if ~use_hierarchy
        y_vals(sub) = parse_coord(names(sub), position_exp(1));
        x_vals(sub) = parse_coord(names(sub), position_exp(2));
        z_vals(sub) = parse_coord(names(sub), position_exp(3));
    else
        all_nums = regexp(names(sub), '\d+', 'match');
        y_vals(sub) = cellfun(@(m) str2double(m{1}), all_nums);
        x_vals(sub) = cellfun(@(m) str2double(m{2}), all_nums);
        z_vals(sub) = cellfun(@(m) str2double(m{3}), all_nums);
    end
    pct = k / n_chunks;
    filled = round(pct * bar_width);
    bar_str = [repmat('=', 1, filled), repmat(' ', 1, bar_width - filled)];
    fprintf('\r  Parsing %d %s files: [%s] %3d%%', n, marker, bar_str, round(pct * 100));
end
fprintf('\n');

if any(isnan(z_vals))
    bad_names = names(isnan(z_vals));
    if all(contains(bad_names, 'stitched.tif'))
        path_sub = munge_stitched(path_idx);
        return
    elseif all(contains(bad_names, 'aligned.tif'))
        path_sub = munge_aligned(path_idx);
        return
    else
        error("Error reading file: %s", files{find(isnan(z_vals), 1)})
    end
end

path_sub = struct( ...
    'file',        files, ...
    'sample_id',   repmat({sample_id}, n, 1), ...
    'y',           num2cell(y_vals), ...
    'x',           num2cell(x_vals), ...
    'z',           num2cell(z_vals), ...
    'channel_num', num2cell(repmat(channel, n, 1)), ...
    'markers',     repmat({marker}, n, 1) ...
);
end


function vals = parse_coord(names, pattern)
if pattern == ""
    vals = ones(length(names), 1);
else
    matches = regexp(names, char(pattern), 'match', 'once');
    vals = str2double(regexprep(matches, '[^\d+]', ''));
end
end


function coords = cluster_coords(coords, tolerance)
% Snap values in coords so that any two values within tolerance of each
% other share the same canonical value (the smallest in each cluster).
vals = sort(unique(coords));
canonical = vals;
for k = 2:length(vals)
    if vals(k) - canonical(k-1) <= tolerance
        canonical(k) = canonical(k-1);
    end
end
for k = 1:length(vals)
    coords(coords == vals(k)) = canonical(k);
end
end